#!/bin/bash

function createMiningcompany() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/miningcompany.tantalum.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/miningcompany.tantalum.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-miningcompany --tls.certfiles "${PWD}/organizations/fabric-ca/miningcompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-miningcompany.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-miningcompany.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-miningcompany.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-miningcompany.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/miningcompany.tantalum.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy miningcompany's CA cert to miningcompany's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/miningcompany.tantalum.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/miningcompany/ca-cert.pem" "${PWD}/organizations/peerOrganizations/miningcompany.tantalum.com/msp/tlscacerts/ca.crt"

  # Copy miningcompany's CA cert to miningcompany's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/miningcompany.tantalum.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/miningcompany/ca-cert.pem" "${PWD}/organizations/peerOrganizations/miningcompany.tantalum.com/tlsca/tlsca.miningcompany.tantalum.com-cert.pem"

  # Copy miningcompany's CA cert to miningcompany's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/miningcompany.tantalum.com/ca"
  cp "${PWD}/organizations/fabric-ca/miningcompany/ca-cert.pem" "${PWD}/organizations/peerOrganizations/miningcompany.tantalum.com/ca/ca.miningcompany.tantalum.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-miningcompany --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/miningcompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-miningcompany --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/miningcompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-miningcompany --id.name miningcompanyadmin --id.secret miningcompanyadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/miningcompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-miningcompany -M "${PWD}/organizations/peerOrganizations/miningcompany.tantalum.com/peers/peer0.miningcompany.tantalum.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/miningcompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/miningcompany.tantalum.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/miningcompany.tantalum.com/peers/peer0.miningcompany.tantalum.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-miningcompany -M "${PWD}/organizations/peerOrganizations/miningcompany.tantalum.com/peers/peer0.miningcompany.tantalum.com/tls" --enrollment.profile tls --csr.hosts peer0.miningcompany.tantalum.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/miningcompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/miningcompany.tantalum.com/peers/peer0.miningcompany.tantalum.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/miningcompany.tantalum.com/peers/peer0.miningcompany.tantalum.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/miningcompany.tantalum.com/peers/peer0.miningcompany.tantalum.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/miningcompany.tantalum.com/peers/peer0.miningcompany.tantalum.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/miningcompany.tantalum.com/peers/peer0.miningcompany.tantalum.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/miningcompany.tantalum.com/peers/peer0.miningcompany.tantalum.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-miningcompany -M "${PWD}/organizations/peerOrganizations/miningcompany.tantalum.com/users/User1@miningcompany.tantalum.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/miningcompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/miningcompany.tantalum.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/miningcompany.tantalum.com/users/User1@miningcompany.tantalum.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://miningcompanyadmin:miningcompanyadminpw@localhost:7054 --caname ca-miningcompany -M "${PWD}/organizations/peerOrganizations/miningcompany.tantalum.com/users/Admin@miningcompany.tantalum.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/miningcompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/miningcompany.tantalum.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/miningcompany.tantalum.com/users/Admin@miningcompany.tantalum.com/msp/config.yaml"
}

function createRefiningcompany() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/refiningcompany.tantalum.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/refiningcompany.tantalum.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-refiningcompany --tls.certfiles "${PWD}/organizations/fabric-ca/refiningcompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-refiningcompany.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-refiningcompany.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-refiningcompany.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-refiningcompany.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/refiningcompany.tantalum.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy refiningcompany's CA cert to refiningcompany's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/refiningcompany.tantalum.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/refiningcompany/ca-cert.pem" "${PWD}/organizations/peerOrganizations/refiningcompany.tantalum.com/msp/tlscacerts/ca.crt"

  # Copy refiningcompany's CA cert to refiningcompany's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/refiningcompany.tantalum.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/refiningcompany/ca-cert.pem" "${PWD}/organizations/peerOrganizations/refiningcompany.tantalum.com/tlsca/tlsca.refiningcompany.tantalum.com-cert.pem"

  # Copy refiningcompany's CA cert to refiningcompany's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/refiningcompany.tantalum.com/ca"
  cp "${PWD}/organizations/fabric-ca/refiningcompany/ca-cert.pem" "${PWD}/organizations/peerOrganizations/refiningcompany.tantalum.com/ca/ca.refiningcompany.tantalum.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-refiningcompany --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/refiningcompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-refiningcompany --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/refiningcompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-refiningcompany --id.name refiningcompanyadmin --id.secret refiningcompanyadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/refiningcompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-refiningcompany -M "${PWD}/organizations/peerOrganizations/refiningcompany.tantalum.com/peers/peer0.refiningcompany.tantalum.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/refiningcompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/refiningcompany.tantalum.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/refiningcompany.tantalum.com/peers/peer0.refiningcompany.tantalum.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-refiningcompany -M "${PWD}/organizations/peerOrganizations/refiningcompany.tantalum.com/peers/peer0.refiningcompany.tantalum.com/tls" --enrollment.profile tls --csr.hosts peer0.refiningcompany.tantalum.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/refiningcompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/refiningcompany.tantalum.com/peers/peer0.refiningcompany.tantalum.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/refiningcompany.tantalum.com/peers/peer0.refiningcompany.tantalum.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/refiningcompany.tantalum.com/peers/peer0.refiningcompany.tantalum.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/refiningcompany.tantalum.com/peers/peer0.refiningcompany.tantalum.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/refiningcompany.tantalum.com/peers/peer0.refiningcompany.tantalum.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/refiningcompany.tantalum.com/peers/peer0.refiningcompany.tantalum.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-refiningcompany -M "${PWD}/organizations/peerOrganizations/refiningcompany.tantalum.com/users/User1@refiningcompany.tantalum.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/refiningcompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/refiningcompany.tantalum.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/refiningcompany.tantalum.com/users/User1@refiningcompany.tantalum.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://refiningcompanyadmin:refiningcompanyadminpw@localhost:8054 --caname ca-refiningcompany -M "${PWD}/organizations/peerOrganizations/refiningcompany.tantalum.com/users/Admin@refiningcompany.tantalum.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/refiningcompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/refiningcompany.tantalum.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/refiningcompany.tantalum.com/users/Admin@refiningcompany.tantalum.com/msp/config.yaml"
}


function createManufacturingcompany() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/manufacturingcompany.tantalum.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/manufacturingcompany.tantalum.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:11054 --caname ca-manufacturingcompany --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturingcompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-manufacturingcompany.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-manufacturingcompany.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-manufacturingcompany.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-11054-ca-manufacturingcompany.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/manufacturingcompany.tantalum.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy manufacturingcompany's CA cert to manufacturingcompany's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/manufacturingcompany.tantalum.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/manufacturingcompany/ca-cert.pem" "${PWD}/organizations/peerOrganizations/manufacturingcompany.tantalum.com/msp/tlscacerts/ca.crt"

  # Copy manufacturingcompany's CA cert to manufacturingcompany's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/manufacturingcompany.tantalum.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/manufacturingcompany/ca-cert.pem" "${PWD}/organizations/peerOrganizations/manufacturingcompany.tantalum.com/tlsca/tlsca.manufacturingcompany.tantalum.com-cert.pem"

  # Copy manufacturingcompany's CA cert to manufacturingcompany's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/manufacturingcompany.tantalum.com/ca"
  cp "${PWD}/organizations/fabric-ca/manufacturingcompany/ca-cert.pem" "${PWD}/organizations/peerOrganizations/manufacturingcompany.tantalum.com/ca/ca.manufacturingcompany.tantalum.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-manufacturingcompany --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturingcompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-manufacturingcompany --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturingcompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-manufacturingcompany --id.name manufacturingcompanyadmin --id.secret manufacturingcompanyadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturingcompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-manufacturingcompany -M "${PWD}/organizations/peerOrganizations/manufacturingcompany.tantalum.com/peers/peer0.manufacturingcompany.tantalum.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturingcompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/manufacturingcompany.tantalum.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/manufacturingcompany.tantalum.com/peers/peer0.manufacturingcompany.tantalum.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca-manufacturingcompany -M "${PWD}/organizations/peerOrganizations/manufacturingcompany.tantalum.com/peers/peer0.manufacturingcompany.tantalum.com/tls" --enrollment.profile tls --csr.hosts peer0.manufacturingcompany.tantalum.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturingcompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/manufacturingcompany.tantalum.com/peers/peer0.manufacturingcompany.tantalum.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/manufacturingcompany.tantalum.com/peers/peer0.manufacturingcompany.tantalum.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/manufacturingcompany.tantalum.com/peers/peer0.manufacturingcompany.tantalum.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/manufacturingcompany.tantalum.com/peers/peer0.manufacturingcompany.tantalum.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/manufacturingcompany.tantalum.com/peers/peer0.manufacturingcompany.tantalum.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/manufacturingcompany.tantalum.com/peers/peer0.manufacturingcompany.tantalum.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:11054 --caname ca-manufacturingcompany -M "${PWD}/organizations/peerOrganizations/manufacturingcompany.tantalum.com/users/User1@manufacturingcompany.tantalum.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturingcompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/manufacturingcompany.tantalum.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/manufacturingcompany.tantalum.com/users/User1@manufacturingcompany.tantalum.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://manufacturingcompanyadmin:manufacturingcompanyadminpw@localhost:11054 --caname ca-manufacturingcompany -M "${PWD}/organizations/peerOrganizations/manufacturingcompany.tantalum.com/users/Admin@manufacturingcompany.tantalum.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturingcompany/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/manufacturingcompany.tantalum.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/manufacturingcompany.tantalum.com/users/Admin@manufacturingcompany.tantalum.com/msp/config.yaml"
}

function createCertificationauthority() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/certificationauthority.tantalum.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/certificationauthority.tantalum.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:12054 --caname ca-certificationauthority --tls.certfiles "${PWD}/organizations/fabric-ca/certificationauthority/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-12054-ca-certificationauthority.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-12054-ca-certificationauthority.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-12054-ca-certificationauthority.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-12054-ca-certificationauthority.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/certificationauthority.tantalum.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy certificationauthority's CA cert to certificationauthority's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/certificationauthority.tantalum.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/certificationauthority/ca-cert.pem" "${PWD}/organizations/peerOrganizations/certificationauthority.tantalum.com/msp/tlscacerts/ca.crt"

  # Copy certificationauthority's CA cert to certificationauthority's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/certificationauthority.tantalum.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/certificationauthority/ca-cert.pem" "${PWD}/organizations/peerOrganizations/certificationauthority.tantalum.com/tlsca/tlsca.certificationauthority.tantalum.com-cert.pem"

  # Copy certificationauthority's CA cert to certificationauthority's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/certificationauthority.tantalum.com/ca"
  cp "${PWD}/organizations/fabric-ca/certificationauthority/ca-cert.pem" "${PWD}/organizations/peerOrganizations/certificationauthority.tantalum.com/ca/ca.certificationauthority.tantalum.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-certificationauthority --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/certificationauthority/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca-certificationauthority --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/certificationauthority/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-certificationauthority --id.name certificationauthorityadmin --id.secret certificationauthorityadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/certificationauthority/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:12054 --caname ca-certificationauthority -M "${PWD}/organizations/peerOrganizations/certificationauthority.tantalum.com/peers/peer0.certificationauthority.tantalum.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/certificationauthority/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/certificationauthority.tantalum.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/certificationauthority.tantalum.com/peers/peer0.certificationauthority.tantalum.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:12054 --caname ca-certificationauthority -M "${PWD}/organizations/peerOrganizations/certificationauthority.tantalum.com/peers/peer0.certificationauthority.tantalum.com/tls" --enrollment.profile tls --csr.hosts peer0.certificationauthority.tantalum.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/certificationauthority/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/certificationauthority.tantalum.com/peers/peer0.certificationauthority.tantalum.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/certificationauthority.tantalum.com/peers/peer0.certificationauthority.tantalum.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/certificationauthority.tantalum.com/peers/peer0.certificationauthority.tantalum.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/certificationauthority.tantalum.com/peers/peer0.certificationauthority.tantalum.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/certificationauthority.tantalum.com/peers/peer0.certificationauthority.tantalum.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/certificationauthority.tantalum.com/peers/peer0.certificationauthority.tantalum.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:12054 --caname ca-certificationauthority -M "${PWD}/organizations/peerOrganizations/certificationauthority.tantalum.com/users/User1@certificationauthority.tantalum.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/certificationauthority/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/certificationauthority.tantalum.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/certificationauthority.tantalum.com/users/User1@certificationauthority.tantalum.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://certificationauthorityadmin:certificationauthorityadminpw@localhost:12054 --caname ca-certificationauthority -M "${PWD}/organizations/peerOrganizations/certificationauthority.tantalum.com/users/Admin@certificationauthority.tantalum.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/certificationauthority/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/certificationauthority.tantalum.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/certificationauthority.tantalum.com/users/Admin@certificationauthority.tantalum.com/msp/config.yaml"
}


function createOrderer() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/tantalum.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/tantalum.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/tantalum.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/tantalum.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/tantalum.com/msp/tlscacerts/tlsca.tantalum.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/tantalum.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/tantalum.com/tlsca/tlsca.tantalum.com-cert.pem"

  echo "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/tantalum.com/orderers/orderer.tantalum.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/tantalum.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/tantalum.com/orderers/orderer.tantalum.com/msp/config.yaml"

  echo "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/tantalum.com/orderers/orderer.tantalum.com/tls" --enrollment.profile tls --csr.hosts orderer.tantalum.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/tantalum.com/orderers/orderer.tantalum.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/tantalum.com/orderers/orderer.tantalum.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/tantalum.com/orderers/orderer.tantalum.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/tantalum.com/orderers/orderer.tantalum.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/tantalum.com/orderers/orderer.tantalum.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/tantalum.com/orderers/orderer.tantalum.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/tantalum.com/orderers/orderer.tantalum.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/tantalum.com/orderers/orderer.tantalum.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/tantalum.com/orderers/orderer.tantalum.com/msp/tlscacerts/tlsca.tantalum.com-cert.pem"

  echo "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/tantalum.com/users/Admin@tantalum.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/tantalum.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/tantalum.com/users/Admin@tantalum.com/msp/config.yaml"
}

createMiningcompany
createRefiningcompany
createManufacturingcompany
createCertificationauthority
createOrderer
